### ISSUE TITLE
Scenario Layout

### ISSUE THREAD

**Issue by schmidni** [swiss-seismological-service/REIA-web#15]
### User Story
As a person who looks at the sheets I always need to have the correct version, either Scenario or RIA, of the sheet.

### Acceptance Criteria
Whether the version is automatically changed depending on the metadata or whether an installation always shows one of the two has to be decided. But the two versions need to be managed easily and with as little overhead and duplication as possible in code.

**Comment by schmidni** [comment]
[version_szn.pdf](https://github.com/swiss-seismological-service/REIA-web/files/13472498/version_szn.pdf)



[version_ria.pdf](https://github.com/swiss-seismological-service/REIA-web/files/13472500/version_ria.pdf)

**Comment by romanoe** [comment]
Regarding the *Weitere Ereignisdaten* link: Since the href link is generated within the `InfoTable` component and the `getOriginInfo` endpoint doesn't contain the type (either 'natural' or 'scenario'), how should this be approached? Should we call `getAllRiskAssessments` within [AddOriginInfo](https://github.com/swiss-seismological-service/REIA-web/blob/c9612c04fc98635aa8486b5b7d6529aedc2ccf35/src/js/components/DataComponent.js#L118) to retrieve this information and changing the the originInfo href on the fly, or should it be made available through the `getOriginInfo` endpoint (REIA-ws) thereby making the href dependent on the 'type'?

**Comment by schmidni** [comment]
philipp described the evaluationmode here, it has nothing to do with scenario: https://github.com/swiss-seismological-service/REIA-ws/issues/7#issuecomment-1842678470 :)

depends on how you are controlling everything. If you change the information for the scenario type from one central place, I would just do the same and change/hide/update the href from the same central place.

Otherwise you could also add another attribute on the InfoTable to control the link from the outside. I think none of the solutions are pretty.

**Comment by kaestli** [comment]
sorry this question from the side line: but why not adding the scenario/real flag to the origin info response? It is kind of relevant if you are in a mixed-content environment...
